// js/views/zones/index.js

export async function renderZonesTab() {
    const containerId = 'zones-tab-content';
    
    // We use a small delay to ensure the container is in the DOM
    setTimeout(async () => {
        const container = document.getElementById(containerId);
        if (!container) return;

        try {
            // Fetch the definitions generated by your Python script
            const response = await fetch('data/zones/zones.json');
            if (!response.ok) throw new Error("Zones JSON not found");
            const data = await response.json();

            // Render the split-view for Cycling and Running
            container.innerHTML = `
                <div class="grid grid-cols-1 lg:grid-cols-2 gap-8 p-4">
                    ${renderZoneCard("Cycling Power Zones", data.cycling, "text-purple-400")}
                    ${renderZoneCard("Running HR Zones", data.running, "text-pink-400")}
                </div>
            `;
        } catch (err) {
            console.error("Zones Load Error:", err);
            container.innerHTML = `
                <div class="p-8 text-center text-slate-500">
                    <p class="italic">No zone definitions found. Please run the zone generation script.</p>
                </div>
            `;
        }
    }, 50);

    // Initial placeholder while data loads
    return `<div id="${containerId}" class="min-h-[400px]"></div>`;
}

/**
 * Internal helper to build the individual zone cards
 */
function renderZoneCard(title, sportData, iconColor) {
    if (!sportData || !sportData.zones) return '';

    const rows = sportData.zones.map(z => `
        <div class="flex justify-between items-center py-3 border-b border-slate-700/50 last:border-0 hover:bg-slate-700/20 px-2 rounded transition-colors">
            <span class="text-sm font-bold text-slate-200">${z.name}</span>
            <span class="text-sm font-mono font-bold text-white bg-slate-900/50 px-3 py-1 rounded border border-slate-700">
                ${z.range}
            </span>
        </div>
    `).join('');

    return `
        <div class="bg-slate-800/50 border border-slate-700 rounded-2xl p-6 shadow-xl backdrop-blur-sm">
            <div class="flex items-center justify-between mb-6">
                <h3 class="text-xl font-bold text-white flex items-center gap-3">
                    <i class="fa-solid fa-bolt-lightning ${iconColor}"></i>
                    ${title}
                </h3>
                <span class="text-[10px] font-black uppercase tracking-widest text-slate-500 bg-slate-900 px-2 py-1 rounded">
                    ${sportData.type}
                </span>
            </div>
            
            <div class="space-y-1">
                <div class="flex justify-between text-[10px] font-bold text-slate-500 uppercase tracking-tighter px-2 mb-2">
                    <span>Intensity Level</span>
                    <span>Range (${sportData.unit})</span>
                </div>
                ${rows}
            </div>
        </div>
    `;
}
