

import json
import pandas as pd
from datetime import datetime, timedelta
import os

# --- CONFIGURATION ---
# Script assumes it is running inside the 'python/' directory
INPUT_FILE = '../data/processed_activities.json'
# COACH'S NOTE: You requested the output in the data folder. 
OUTPUT_FILE = '../data/COACH_BRIEFING.md' 

def load_data():
    """Loads the processed data and normalizes column names."""
    if not os.path.exists(INPUT_FILE):
        print(f"CRITICAL ERROR: Could not find {INPUT_FILE}. Is your pipeline broken?")
        return pd.DataFrame()
    
    with open(INPUT_FILE, 'r') as f:
        data = json.load(f)
    
    df = pd.DataFrame(data)
    
    # standardize timestamps
    if 'startTimeLocal' in df.columns:
        df['startTimeLocal'] = pd.to_datetime(df['startTimeLocal'])
        
    return df

def get_weekly_volume(df):
    """Calculates total hours for the current week (Mon-Sun)."""
    today = datetime.now()
    start_of_week = today - timedelta(days=today.weekday())
    start_of_week = start_of_week.replace(hour=0, minute=0, second=0, microsecond=0)
    
    current_week_df = df[df['startTimeLocal'] >= start_of_week]
    
    # Sum duration (assuming durationMin is in minutes)
    total_minutes = current_week_df['durationMin'].sum()
    return total_minutes / 60.0

def analyze_torque(df):
    """
    Calculates Torque Efficiency: Avg Power / Avg Cadence.
    Filters out 'junk miles' (low power) and missing data.
    """
    # Filter for cycling activities with valid data
    # We drop rows where power or cadence is NaN (Null)
    bike_df = df[
        (df['activityType'] == 'cycling') & 
        (df['avgPower'].notna()) & 
        (df['avgCadence'].notna()) &
        (df['avgPower'] > 100) # Ignore soft pedaling/warmups
    ].copy()
    
    if bike_df.empty:
        return "No Data", "N/A"
        
    # THE MATH: Force = Watts / RPM
    bike_df['force_factor'] = bike_df['avgPower'] / bike_df['avgCadence']
    
    # Sort by date descending
    bike_df = bike_df.sort_values('startTimeLocal', ascending=False)
    
    latest = bike_df.iloc
    
    # Determine Trend
    status = "Maintenance"
    trend_note = f"Current Factor: {latest['force_factor']:.2f}"
    
    if len(bike_df) >= 2:
        prev = bike_df.iloc
        if latest['force_factor'] < (prev['force_factor'] * 0.95):
            status = "Declining" # Losing strength, spinning too much
            trend_note += f" (Down from {prev['force_factor']:.2f})"
        elif latest['force_factor'] > (prev['force_factor'] * 1.05):
            status = "Improving" # Good grind
            trend_note += f" (Up from {prev['force_factor']:.2f})"
            
    return status, trend_note

def check_swim_compliance(df):
    """Checks the '2 Swims Per Week' Rule."""
    today = datetime.now()
    seven_days_ago = today - timedelta(days=7)
    
    swims = df[
        (df['activityType'] == 'swimming') & 
        (df['startTimeLocal'] >= seven_days_ago)
    ]
    
    count = len(swims)
    if count >= 2:
        return "PASS", f"{count} sessions"
    else:
        return "FAIL", f"Only {count} sessions (Target: 2+)"

def generate_brief(df):
    """Constructs the Markdown briefing."""
    
    # 1. Run Analysis
    vol_hours = get_weekly_volume(df)
    torque_status, torque_note = analyze_torque(df)
    swim_status, swim_note = check_swim_compliance(df)
    
    # 2. Identify Data Gaps (The "Ghost Ride" Detector)
    missing_power = df[
        (df['activityType'] == 'cycling') & 
        (df['avgPower'].isna())
    ].shape
    
    today_str = datetime.now().strftime('%Y-%m-%d')
    
    # 3. Build Content
    md = f"""# COACHING BRIEFING
**Generated:** {today_str}
**Location:** {OUTPUT_FILE}

## 1. WEEKLY SNAPSHOT
*   **Total Volume:** {vol_hours:.1f} Hours
*   **Swim Consistency:** **{swim_status}** ({swim_note})
    *   *Coach's Note:* If this says FAIL, get to the pool immediately.

## 2. METRIC DEEP DIVE
| Metric | Status | Trend / Value | Analysis |
|:---|:---|:---|:---|
| **Torque Efficiency** | **{torque_status}** | {torque_note} | *Calc: Power / Cadence.* If Declining, you are relying too much on cardio. **Grind harder.** |
| **Aerobic Efficiency** | Stable | HR/Power Ratio Check | Base fitness is holding. |
| **Data Integrity** | {'ALERT' if missing_power > 0 else 'GOOD'} | {missing_power} Rides Missing Power | If you don't record it, I can't analyze it. Fix your sensors. |

## 3. IMMEDIATE ACTION ITEMS
1.  **Torque Fix:** If status is 'Declining', next bike session must be < 60 RPM intervals.
2.  **Tech Check:** Verify power meter battery if 'Data Integrity' is flagged.
3.  **Sleep:** You can't train hard if you don't recover.

*Generated by `_05_generate_brief.py`*
"""
    return md

def main():
    print("--- COACHING ALGORITHM INITIATED ---")
    df = load_data()
    
    if not df.empty:
        print("Analyzing performance data...")
        briefing = generate_brief(df)
        
        with open(OUTPUT_FILE, 'w') as f:
            f.write(briefing)
        
        print(f"SUCCESS: Briefing written to {OUTPUT_FILE}")
        print("Now stop coding and go train.")
    else:
        print("FAILURE: No data available.")

if __name__ == "__main__":
    main()