// js/views/dashboard/heatmaps.js
import { buildCollapsibleSection, getSportColorVar } from './utils.js';

export function renderHeatmaps() {
    // 1. Initial Shell with Loading State
    const containerId = 'heatmap-grids-container';
    
    // Use a small delay to ensure the container is in the DOM before fetching
    setTimeout(async () => {
        const container = document.getElementById(containerId);
        if (!container) return;

        try {
            // FETCH THE NEW PRE-CALCULATED DATA
            const response = await fetch('data/dashboard/heatmaps.json');
            if (!response.ok) throw new Error("Heatmap data not found");
            const data = await response.json();

            // Populate the three grids using the pre-calculated logic
            container.innerHTML = `
                ${renderGrid("Recent Consistency (Compliance)", data, "compliance")}
                ${renderGrid("Activity Log (Sport Intensity)", data, "activity")}
                ${renderGrid("Annual Overview", data, "compliance", true)}
            `;
        } catch (err) {
            console.error("Heatmap Load Error:", err);
            container.innerHTML = `<p class="text-slate-500 italic p-4">Error loading heatmap data.</p>`;
        }
    }, 100);

    const loadingShell = `<div id="${containerId}" class="flex flex-col gap-8 min-h-[200px] justify-center items-center text-slate-500 italic">
        <i class="fa-solid fa-circle-notch fa-spin mr-2"></i> Initializing Heatmaps...
    </div>`;

    return buildCollapsibleSection('heatmaps-section', 'Training Heatmaps', loadingShell, true);
}

function renderGrid(title, data, mode, fullYear = false) {
    // Grid Setup
    const today = new Date();
    const startDate = new Date();
    if (fullYear) {
        startDate.setMonth(0, 1); // Start of current year
    } else {
        startDate.setMonth(today.getMonth() - 6); // Trailing 6 months
    }

    // Logic to build the grid squares
    let gridHtml = '';
    const dayLabels = ['M', 'T', 'W', 'T', 'F', 'S', 'S'];
    
    // We group data by date for O(1) lookup
    const dataMap = {};
    data.forEach(item => { dataMap[item.date] = item; });

    // Iterate through dates to create cells
    let current = new Date(startDate);
    while (current <= today) {
        const dateStr = current.toISOString().split('T')[0];
        const dayOfWeek = current.getDay(); // 0 is Sunday
        const item = dataMap[dateStr];

        // Apply Sunday Filter: Sundays only show if they have a workout (from Python data)
        if (dayOfWeek === 0 && !item) {
            current.setDate(current.getDate() + 1);
            continue;
        }

        // Determine Color based on Mode
        let bgColor = 'bg-slate-800'; // Default Empty/Rest
        let tooltipText = `${dateStr}: Rest Day`;

        if (item) {
            if (mode === 'compliance') {
                // Use the complianceStatus generated by Python
                const status = item.complianceStatus;
                if (status === 'Completed') bgColor = 'bg-emerald-500';
                if (status === 'Partial') bgColor = 'bg-yellow-500';
                if (status === 'Missed') bgColor = 'bg-red-500';
                if (status === 'Unplanned') bgColor = 'bg-blue-400';
            } else {
                // Activity Mode: Use Sport Colors
                bgColor = `style="background-color: ${getSportColorVar(item.actualSport)}"`;
            }
            tooltipText = `${dateStr}: ${item.activityName || item.complianceStatus}`;
        }

        gridHtml += `<div class="w-3 h-3 rounded-sm ${bgColor.startsWith('bg') ? bgColor : ''}" 
                          ${bgColor.startsWith('style') ? bgColor : ''} 
                          onmouseover="window.showDashboardTooltip(event, '${dateStr}', ${item?.plannedDuration || 0}, ${item?.actualDuration || 0}, '${item?.complianceStatus || 'Rest'}', '', '${item?.actualSport || ''}', '')">
                     </div>`;
        
        current.setDate(current.getDate() + 1);
    }

    return `
        <div class="mb-4">
            <h4 class="text-[10px] uppercase tracking-widest text-slate-500 font-bold mb-2">${title}</h4>
            <div class="flex flex-wrap gap-1">
                ${gridHtml}
            </div>
        </div>
    `;
}
