import { getIcon, getSportColorVar, buildCollapsibleSection } from './utils.js';

export function renderPlannedWorkouts() {
    setTimeout(async () => {
        const container = document.getElementById('planned-workouts-content');
        if (!container) return;
        
        try {
            // 1. Fetch the specific file generated by Python
            const response = await fetch('data/dashboard/plannedWorkouts.json');
            if (!response.ok) throw new Error("Schedule file not found");
            
            let data = await response.json();
            
            // 2. Sort Chronologically (Oldest -> Newest)
            // If you prefer Newest first, swap a and b
            data.sort((a, b) => new Date(a.date) - new Date(b.date));

            // 3. Render
            container.innerHTML = generateCardsHTML(data);
            
            // Optional: Scroll 'Today' into view if the list is long
            setTimeout(() => {
                const todayCard = container.querySelector('.ring-blue-500');
                if (todayCard) todayCard.scrollIntoView({ behavior: 'smooth', block: 'center' });
            }, 500);
            
        } catch (error) {
            console.error("Failed to load schedule:", error);
            container.innerHTML = `<p class="text-slate-500 italic p-4">Unable to load schedule.</p>`;
        }
    }, 50);

    const loadingHtml = `<div id="planned-workouts-content" class="min-h-[100px] flex items-center justify-center text-slate-500">
        <i class="fa-solid fa-circle-notch fa-spin mr-2"></i> Loading Schedule...
    </div>`;

    return buildCollapsibleSection('planned-workouts-section', 'Planned Workouts', loadingHtml, true);
}

function generateCardsHTML(data) {
    if (!data || data.length === 0) {
        return '<p class="text-slate-500 italic p-4">No workouts found.</p>';
    }

    let cardsHtml = '';
    const todayStr = new Date().toISOString().split('T')[0];

    data.forEach(w => {
        let statusColor = "text-white";
        let cardBorder = "border border-slate-700 hover:border-slate-600";
        let durationDisplay = `${Math.round(w.plannedDuration)} min`;
        
        // --- 1. Visuals based on Actual Sport (or Plan fallback) ---
        // This ensures the icon matches the log if available
        let icon = getIcon(w.actualSport);
        let sportColor = getSportColorVar(w.actualSport);
        
        // --- 2. Highlight Today ---
        if (w.date === todayStr) {
            cardBorder = "ring-2 ring-blue-500 ring-offset-2 ring-offset-slate-900";
        }

        // --- 3. Status Styling ---
        if (w.status === 'COMPLETED' || w.status === 'UNPLANNED') {
            statusColor = "text-emerald-400";
            if (w.date !== todayStr) cardBorder = "ring-1 ring-emerald-500/50 bg-slate-800/80";
            
            // Show Actual vs Planned
            durationDisplay = `<span class="text-emerald-400">${Math.round(w.actualDuration)}</span> / ${Math.round(w.plannedDuration)} min`;
            
        } else if (w.status === 'MISSED') {
            statusColor = "text-red-400";
            cardBorder = "border border-red-900/30 opacity-75";
        } else if (w.status === 'REST') {
            statusColor = "text-slate-500";
            cardBorder = "border border-slate-800 opacity-50";
            durationDisplay = "--";
        }

        // --- 4. Content Cleanup ---
        const cleanNotes = w.notes ? w.notes.replace(/\[.*?\]/g, '').trim() : '';
        const title = w.plannedWorkout || (w.status === 'REST' ? 'Rest Day' : 'Workout');
        const dayLabel = w.day || w.date;

        cardsHtml += `
            <div class="bg-slate-800 rounded-lg p-4 shadow-md relative overflow-hidden transition-all ${cardBorder} flex flex-col gap-3 group min-h-[140px]">
                
                <div class="flex justify-between items-start">
                    <div class="flex flex-col">
                        <span class="text-[10px] uppercase tracking-widest text-slate-400 font-bold">${dayLabel}</span>
                        <span class="text-xs text-slate-500">${w.date}</span>
                    </div>
                    <div class="opacity-80 transition-transform group-hover:scale-110" style="color:${sportColor}">
                        ${icon}
                    </div>
                </div>

                <div>
                    <h3 class="text-md font-bold text-white leading-tight mb-1 truncate" title="${title}">
                        ${title}
                    </h3>
                    <div class="flex justify-between items-center mt-2">
                        <span class="text-xs font-bold ${statusColor} uppercase tracking-wider">${w.status}</span>
                        <span class="text-sm font-mono text-slate-300 bg-slate-700/50 px-2 py-1 rounded">${durationDisplay}</span>
                    </div>
                </div>

                ${cleanNotes ? `
                <div class="pt-2 border-t border-slate-700/50 mt-auto">
                    <p class="text-[11px] text-slate-400 line-clamp-2 leading-relaxed" title="${cleanNotes}">${cleanNotes}</p>
                </div>` : ''}
            </div>
        `;
    });

    return `<div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4 p-2">${cardsHtml}</div>`;
}